'use client';
import { useEffect, useRef, useState, type ReactNode } from 'react';
export const human = (s: string) => s.replaceAll('_', ' ').replace(/^./, c => c.toUpperCase());
export const dateLabel = (s: string) => s ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(s.length === 10 ? `${s}T12:00:00Z` : s)) : 'Not scheduled';
export function Badge({ children, tone = '' }: { children: ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span>; }
export function Empty({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <div className="empty"><span className="empty-mark" aria-hidden="true">✓</span><h3>{title}</h3><p>{detail}</p>{action}</div>; }
export function Panel({ title, detail, action, children }: { title: string; detail?: string; action?: ReactNode; children: ReactNode }) { return <section className="panel"><div className="panel-heading"><div><h2>{title}</h2>{detail && <p>{detail}</p>}</div>{action}</div>{children}</section>; }
export type Values = Record<string, string | boolean | string[]>;
export interface Field { name: string; label: string; type?: 'text' | 'textarea' | 'select' | 'date' | 'number' | 'email' | 'checkbox' | 'multi'; options?: { value: string; label: string }[]; required?: boolean; hint?: string; show?: (values: Values) => boolean; max?: number }
export interface DialogSpec { title: string; description?: string; fields?: Field[]; initial?: Values; submit?: string; save?: (values: Values) => Promise<void>; content?: ReactNode }
export function Dialog({ spec, onClose }: { spec: DialogSpec; onClose: () => void }) { const [values, setValues] = useState<Values>(spec.initial || {}); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const root = useRef<HTMLDivElement>(null); const closeRef = useRef(onClose); closeRef.current = onClose;
  useEffect(() => { const prior = document.activeElement as HTMLElement | null; root.current?.querySelector<HTMLElement>('input,select,textarea,button')?.focus(); const listener = (event: KeyboardEvent) => { if (event.key === 'Escape') closeRef.current(); if (event.key === 'Tab') { const focusables = Array.from(root.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]') || []); const first = focusables[0]; const last = focusables.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }; document.addEventListener('keydown', listener); const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', listener); document.body.style.overflow = overflow; prior?.focus(); }; }, []);
  return <div className="modal-backdrop"><div className="dialog" ref={root} role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header><div><p className="eyebrow">Management workspace</p><h2 id="dialog-title">{spec.title}</h2>{spec.description && <p>{spec.description}</p>}</div><button className="icon-button" type="button" aria-label="Close dialog" disabled={busy} onClick={onClose}>×</button></header><form onSubmit={async event => { event.preventDefault(); if (!spec.save || busy) return; setBusy(true); setError(''); try { await spec.save(values); onClose(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save. Please retry.'); } finally { setBusy(false); } }}><div className="dialog-body">{spec.content}<div className="form-grid">{spec.fields?.filter(f => !f.show || f.show(values)).map(f => <label key={f.name} className={f.type === 'textarea' || f.type === 'multi' || f.type === 'checkbox' ? 'full' : ''}><span>{f.label}{f.required && <span className="required"> *</span>}</span>{f.type === 'textarea' ? <textarea name={f.name} value={String(values[f.name] || '')} required={f.required} maxLength={f.max || 3000} rows={3} onChange={e => setValues({ ...values, [f.name]: e.target.value })}/> : f.type === 'select' || f.type === 'multi' ? <select name={f.name} value={f.type === 'multi' ? (Array.isArray(values[f.name]) ? values[f.name] as string[] : []) : String(values[f.name] || '')} required={f.required} multiple={f.type === 'multi'} onChange={e => setValues({ ...values, [f.name]: f.type === 'multi' ? Array.from(e.target.selectedOptions).map(o => o.value) : e.target.value })}>{f.type !== 'multi' && <option value="">Select…</option>}{f.options?.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select> : f.type === 'checkbox' ? <input name={f.name} type="checkbox" checked={values[f.name] === true} onChange={e => setValues({ ...values, [f.name]: e.target.checked })}/> : <input name={f.name} type={f.type || 'text'} value={String(values[f.name] ?? '')} required={f.required} maxLength={f.max || 3000} min={f.type === 'number' ? 0 : undefined} max={f.type === 'number' ? 100 : undefined} onChange={e => setValues({ ...values, [f.name]: e.target.value })}/>} {f.hint && <small>{f.hint}</small>}</label>)}</div>{error && <p role="alert" className="error">{error}</p>}</div><footer><button className="secondary" type="button" disabled={busy} onClick={onClose}>{spec.save ? 'Cancel' : 'Close'}</button>{spec.save && <button type="submit" disabled={busy}>{busy ? 'Saving…' : spec.submit || 'Save changes'}</button>}</footer></form></div></div>;
}
