'use client';
import type { View, Plan, Expectation, ActionItem, Feedback, Review, RefType, Member } from '@/lib/model';
import { feedbackCategories, closed, todayInZone } from '@/lib/model';
import { Badge, dateLabel, human, type Field, type DialogSpec, type Values } from './ui';
const t = (name: string, label: string, required = true, type: Field['type'] = 'text'): Field => ({ name, label, required, type });
const options = (values: string[]) => values.map(value => ({ value, label: human(value) }));
const sel = (name: string, label: string, values: string[], required = true): Field => ({ ...t(name, label, required, 'select'), options: options(values) });
const daysAfter = (day: string, count: number) => { const d = new Date(`${day}T12:00:00Z`); d.setUTCDate(d.getUTCDate() + count); return d.toISOString().slice(0, 10); };
export function makeForms(v: View, send: (type: string, payload: Record<string, unknown>) => Promise<void>, open: (spec: DialogSpec) => void) {
  const today = todayInZone(v.organization.timezone); const next = daysAfter(today, 7);
  const people = v.members.filter(m => m.active).map(m => ({ value: m.id, label: m.name }));
  const directory = v.directory.map(m => ({ value: m.id, label: m.name }));
  const owner = (label = 'Owner'): Field => ({ ...t('ownerId', label, true, 'select'), options: people });
  const visibility = (): Field => ({ ...t('visibility', 'Who can see this?', true, 'select'), options: [{ value: 'private', label: 'Private — people involved and authorized management' }, { value: 'plan', label: 'Everyone authorized for this plan' }, ...(v.me.role === 'admin' ? [{ value: 'leadership', label: 'Executive only' }] : [])] });
  const sources = (p: Plan): Field => ({ ...t('source', 'Originating record', true, 'select'), options: [{ value: `plan|${p.id}`, label: `Plan: ${p.title}` }, ...v.expectations.filter(x => x.planId === p.id).map(x => ({ value: `expectation|${x.id}`, label: `${human(x.kind)}: ${x.title}` })), ...v.feedback.filter(x => x.planId === p.id).map(x => ({ value: `feedback|${x.id}`, label: `Feedback: ${x.text.slice(0, 70)}` })), ...v.actions.filter(x => x.planId === p.id).map(x => ({ value: `action|${x.id}`, label: `Commitment: ${x.description.slice(0, 70)}` })), ...v.reviews.filter(x => x.planId === p.id).map(x => ({ value: `review|${x.id}`, label: `Review: ${dateLabel(x.scheduledFor)}` })), ...v.meetings.filter(x => x.planId === p.id).map(x => ({ value: `meeting|${x.id}`, label: `Meeting: ${x.title}` })), ...v.decisions.filter(x => x.planId === p.id).map(x => ({ value: `decision|${x.id}`, label: `Decision: ${x.text.slice(0, 70)}` }))] });
  const withSource = (values: Values) => { const [sourceType, sourceId] = String(values.source).split('|'); return { ...values, sourceType, sourceId }; };
  const planFields = [t('title', 'Plan name'), t('purpose', 'Purpose / intended result', true, 'textarea'), t('horizon', 'Time horizon'), t('cadence', 'Review cadence'), t('nextReview', 'Next review', true, 'date')];
  return {
    createPlan(personId = v.me.id) { open({ title: 'Establish a management plan', description: 'Define ownership, expectations, and the next review. Scope and participants are fixed for this plan; changing its purpose preserves a version.', initial: { ownerId: personId, scope: 'individual', horizon: '90-day', cadence: 'Weekly', nextReview: next, visibility: 'participants', participantIds: [] }, fields: [...planFields, owner(), sel('scope', 'Plan level', v.me.role === 'admin' ? ['individual', 'function', 'organization'] : ['individual', 'function']), { ...t('participantIds', 'Additional participants', false, 'multi'), options: people, show: x => x.scope !== 'individual', hint: 'Use Command or Control to select several people.' }, { ...sel('visibility', 'Plan access', v.me.role === 'admin' ? ['participants', 'organization', 'leadership'] : ['participants']), hint: 'Organization access is only allowed for an organizational plan.' }], save: x => send('plan.create', { ...x, participantIds: x.scope === 'individual' ? [] : x.participantIds }) }); },
    revise(p: Plan) { open({ title: 'Revise plan expectations', description: 'The previous version is retained. Participants will be asked to acknowledge the new version.', initial: { title: p.title, purpose: p.purpose, horizon: p.horizon, cadence: p.cadence, nextReview: p.nextReview, status: p.status }, fields: [...planFields, sel('status', 'Plan status', ['active', 'at_risk', 'completed']), t('summary', 'What materially changed?', true, 'textarea')], save: x => send('plan.revise', { ...x, planId: p.id }) }); },
    expectation(p: Plan, e?: Expectation) { open({ title: e ? 'Revise an expectation' : 'Define an expectation', description: 'Every expectation needs an owner, an explicit success measure, and a reporting frequency.', initial: { kind: e?.kind || 'responsibility', title: e?.title || '', description: e?.description || '', ownerId: e?.ownerId || p.ownerId, measure: e?.measure || '', target: e?.target || '', frequency: e?.frequency || p.cadence }, fields: [...(!e ? [sel('kind', 'Expectation type', ['responsibility', 'goal', 'kpi'])] : []), t('title', 'Expectation'), t('description', 'Context', false, 'textarea'), owner(), t('measure', 'Measurement method / unit'), t('target', 'Target / success definition'), t('frequency', 'Reporting frequency'), ...(e ? [t('summary', 'Change summary', true, 'textarea')] : [])], save: x => send('expectation.save', { ...x, planId: p.id, id: e?.id || '' }) }); },
    progress(e: Expectation) { open({ title: 'Report progress', description: e.title, initial: { result: e.result, progress: String(e.progress), status: e.status }, fields: [t('result', 'Current result'), t('progress', 'Progress (%)', true, 'number'), sel('status', 'Current status', ['on_track', 'at_risk', 'blocked', 'complete']), t('note', 'Supporting information', false, 'textarea')], save: x => send('expectation.progress', { ...x, id: e.id }) }); },
    action(p: Plan, followUp = false, sourceType: RefType = 'plan', sourceId = p.id) { open({ title: followUp ? 'Assign a follow-up' : 'Assign a commitment', description: 'A commitment stays open until evidence is submitted and an authorized manager verifies completion.', initial: { ownerId: p.ownerId, dueDate: next, priority: 'normal', source: `${sourceType}|${sourceId}` }, fields: [t('description', 'Required action', true, 'textarea'), owner(), t('dueDate', 'Due date', true, 'date'), sel('priority', 'Priority', ['low', 'normal', 'high']), sources(p), { ...t('kpiId', 'Related KPI', false, 'select'), options: v.expectations.filter(e => e.planId === p.id && e.kind === 'kpi').map(e => ({ value: e.id, label: e.title })) }, ...(followUp ? [t('nextReview', 'Follow-up review date', false, 'date')] : [])], save: x => send(followUp ? 'followup.create' : 'action.create', { ...withSource(x), planId: p.id }) }); },
    actionProgress(a: ActionItem) { open({ title: 'Update commitment', description: a.description, initial: { status: a.status === 'submitted' ? 'submitted' : 'in_progress', evidence: a.evidence }, fields: [sel('status', 'Progress status', ['open', 'in_progress', 'waiting', 'submitted']), t('evidence', 'Completion evidence / progress note', false, 'textarea')], content: <p className="notice">Choose Submitted when the work is ready for verification. Evidence is required for submission; include a result, reference, or supporting link.</p>, save: x => send('action.progress', { ...x, id: a.id }) }); },
    evidence(a: ActionItem, canVerify: boolean) { open({ title: 'Commitment evidence', description: a.description, content: <><div className="detail-grid"><div><small>Owner</small><strong>{v.directory.find(p => p.id === a.ownerId)?.name || 'Assigned owner'}</strong></div><div><small>Due date</small><strong>{dateLabel(a.dueDate)}</strong></div><div><small>Status</small><Badge>{human(a.status)}</Badge></div><div><small>Verified</small><strong>{a.verifiedAt ? dateLabel(a.verifiedAt) : 'Not yet verified'}</strong></div></div><h3>Evidence</h3><p className="preserve">{a.evidence || 'No evidence submitted yet.'}</p><h3>Activity history</h3><div className="timeline">{a.history.map((h, i) => <div key={i}><strong>{human(h.status)}</strong><small>{dateLabel(h.at)} · {v.directory.find(p => p.id === h.by)?.name || 'Authorized manager'}</small><p>{h.evidence}</p></div>)}</div></>, ...(canVerify && a.status === 'submitted' ? { submit: 'Verify completion', save: () => send('action.verify', { id: a.id }) } : {}) }); },
    cancel(a: ActionItem) { open({ title: 'Cancel commitment', description: a.description, fields: [t('reason', 'Reason for cancellation', true, 'textarea')], submit: 'Record cancellation', save: x => send('action.cancel', { ...x, id: a.id }) }); },
    feedback(p: Plan, sourceType: RefType = 'plan', sourceId = p.id) { const recipientId = v.directory.find(m => m.id !== v.me.id && (m.id === p.ownerId || !p.participantIds.includes(m.id)))?.id || p.ownerId; open({ title: 'Share structured feedback', description: 'Reading feedback does not resolve it. A response or explicit resolution is recorded separately.', initial: { category: 'Progress Update', recipientId, visibility: 'private', source: `${sourceType}|${sourceId}`, responseRequired: true, responseDue: next }, fields: [{ ...t('category', 'Feedback type', true, 'select'), options: options(feedbackCategories.filter(c => c !== 'Manager Feedback' || v.me.role !== 'employee')) }, { ...t('recipientId', 'Recipient', true, 'select'), options: directory }, t('text', 'Feedback', true, 'textarea'), sources(p), visibility(), t('responseRequired', 'A response is required', false, 'checkbox'), { ...t('responseDue', 'Response due', true, 'date'), show: x => x.responseRequired === true }], save: x => send('feedback.create', { ...withSource(x), planId: p.id, subjectId: v.me.role === 'employee' ? v.me.id : p.ownerId }) }); },
    respond(f: Feedback) { open({ title: 'Respond to feedback', description: f.category, initial: { response: '', status: 'reviewed' }, content: <><p className="quote">{f.text}</p><p className="subtle">{human(f.visibility)} visibility · {f.actionIds.length} linked commitment(s)</p>{f.response && <p><strong>Previous response:</strong> {f.response}</p>}</>, fields: [t('response', 'Your response', false, 'textarea'), sel('status', 'Disposition', ['acknowledged', 'reviewed', 'resolved'])], save: x => send('feedback.respond', { ...x, id: f.id }) }); },
    schedule(p: Plan) { open({ title: 'Schedule a review', description: p.title, initial: { scheduledFor: p.nextReview || next, title: `${p.title} check-in`, kind: p.scope === 'individual' ? 'Manager / Employee Check-In' : 'Leadership Team', visibility: 'private', agenda: 'Plan status; KPI exceptions; goals at risk; open feedback; overdue commitments; decisions; next review.' }, fields: [t('title', 'Meeting title'), sel('kind', 'Meeting type', ['Owners / Executive Leadership', 'Leadership Team', 'Functional Department', 'Manager / Employee Check-In', 'Performance Review', 'Special Management Review']), t('scheduledFor', 'Review date', true, 'date'), visibility(), t('agenda', 'Agenda', true, 'textarea')], save: x => send('review.schedule', { ...x, planId: p.id, reviewerId: v.me.id, subjectId: p.ownerId }) }); },
    complete(r: Review) { const p = v.plans.find(p => p.id === r.planId)!; const expectations = v.expectations.filter(x => x.planId === p.id); const feedback = v.feedback.filter(x => x.planId === p.id && x.status !== 'resolved'); const actions = v.actions.filter(x => x.planId === p.id && !closed(x.status)); const following = v.followUps.filter(x => x.planId === p.id && !closed(x.status)); const sheet = <div className="review-sheet"><div className="review-sheet-head"><div><p className="eyebrow">Review sheet</p><h3>{p.title}</h3></div><Badge tone={p.status === 'at_risk' ? 'warning' : 'good'}>{human(p.status)}</Badge></div><p>{v.meetings.find(m => m.id === r.meetingId)?.agenda}</p><h4>Expectations & measures</h4>{expectations.length ? expectations.map(e => <div className="sheet-row" key={e.id}><div><strong>{e.title}</strong><small>Target: {e.target} · Current: {e.result || 'Not reported'}</small></div><Badge>{human(e.status)}</Badge></div>) : <p className="subtle">No expectations defined yet.</p>}<h4>Unresolved feedback ({feedback.length})</h4>{feedback.map(f => <p key={f.id}>{f.category}: {f.text}</p>)}<h4>Open commitments ({actions.length}) · Follow-ups ({following.length})</h4>{actions.map(a => <div className="sheet-row" key={a.id}><span>{a.description}</span><Badge tone={a.dueDate < today ? 'danger' : ''}>{a.dueDate < today ? 'Overdue · ' : ''}{dateLabel(a.dueDate)}</Badge></div>)}<h4>Previous decisions</h4>{v.decisions.filter(d => d.planId === p.id).slice(-3).map(d => <p key={d.id}>{d.text}</p>)}</div>;
      if (r.status === 'completed') { open({ title: 'Completed review', description: dateLabel(r.scheduledFor), content: <><p className="quote">{v.decisions.find(d => d.id === r.decisionId)?.text}</p><p className="preserve">{r.notes}</p><p>Outcome: {human(r.outcome)} · Next review: {dateLabel(r.nextReview)}</p></> }); return; }
      const needsAction = (x: Values) => x.outcome === 'follow_up' || x.outcome === 'escalation'; open({ title: 'Conduct review', description: 'Record the decision and begin the next management cycle.', initial: { outcome: 'no_change', nextReview: next, ownerId: p.ownerId, dueDate: next, revisedPurpose: p.purpose }, content: sheet, fields: [t('notes', 'Review notes', false, 'textarea'), sel('outcome', 'Review outcome', ['no_change', 'update_plan', 'follow_up', 'escalation']), t('decision', 'Management decision / rationale', true, 'textarea'), t('nextReview', 'Next review date', true, 'date'), { ...t('revisedPurpose', 'Revised plan purpose', true, 'textarea'), show: x => x.outcome === 'update_plan' }, { ...t('changeSummary', 'Material change summary', true, 'textarea'), show: x => x.outcome === 'update_plan' }, { ...t('description', 'Required follow-up', true, 'textarea'), show: needsAction }, { ...owner(), show: x => x.outcome === 'follow_up' }, { ...t('dueDate', 'Follow-up due date', true, 'date'), show: needsAction }], submit: 'Record decision & continue', save: x => send('review.complete', { ...x, id: r.id }) }); },
    member(m?: Member) { open({ title: m ? 'Update workspace access' : 'Approve a workspace member', description: 'This grants access to the verified owner of the email address. No email is sent automatically; ask the person to activate their account from Sign In.', initial: { email: m?.email || '', name: m?.name || '', jobTitle: m?.jobTitle || '', role: m?.role || 'employee', teamId: m?.teamId || '', active: m?.active ?? true }, fields: [t('email', 'Approved email', true, 'email'), t('name', 'Full name'), t('jobTitle', 'Role / job title', false), sel('role', 'Permission level', ['employee', 'manager', 'admin']), { ...t('teamId', 'Function / team', false, 'select'), options: v.teams.map(t => ({ value: t.id, label: t.name })) }, t('active', 'Access enabled', false, 'checkbox')], save: x => send('member.save', x) }); },
    team() { open({ title: 'Create a function', fields: [t('name', 'Function / team name')], save: x => send('team.create', x) }); },
    organization() { open({ title: 'Organization settings', initial: { name: v.organization.name, timezone: v.organization.timezone }, fields: [t('name', 'Organization name'), t('timezone', 'IANA timezone')], save: x => send('organization.update', x) }); }
  };
}
