import type { State, Member, Plan, Sensitive, RefType, View } from './model';
export class DomainError extends Error { constructor(message: string, public status = 400) { super(message); } }
export function ensure(ok: unknown, message = 'This operation is not permitted.', status = 403): asserts ok { if (!ok) throw new DomainError(message, status); }
export function member(s: State, id: string): Member { const m = s.members.find(x => x.id === id && x.active); ensure(m, 'Choose an active workspace member.', 400); return m; }
export function plan(s: State, id: string): Plan { const p = s.plans.find(x => x.id === id); ensure(p, 'Plan not found.', 404); return p; }
export function managesPerson(a: Member, b: Member) { return a.active && b.active && (a.role === 'admin' || (a.role === 'manager' && ((b.role === 'employee' && Boolean(a.teamId) && a.teamId === b.teamId) || b.id === a.id))); }
export function manages(s: State, a: Member, p: Plan) { const owner = s.members.find(x => x.id === p.ownerId); return a.active && (a.role === 'admin' || (a.role === 'manager' && p.scope !== 'organization' && p.visibility !== 'leadership' && Boolean(a.teamId) && a.teamId === p.teamId && !!owner && managesPerson(a, owner))); }
export function readsPlan(s: State, a: Member, p: Plan) { return a.active && (a.role === 'admin' || manages(s, a, p) || (p.visibility !== 'leadership' && (p.visibility === 'organization' || p.ownerId === a.id || p.participantIds.includes(a.id)))); }
export function readsSensitive(s: State, a: Member, r: Sensitive) { const p = s.plans.find(x => x.id === r.planId); if (!p || !readsPlan(s, a, p)) return false; if (a.role === 'admin') return true; if (r.visibility === 'leadership') return false; return r.visibility === 'plan' || [r.authorId, r.recipientId, r.subjectId].includes(a.id) || manages(s, a, p); }
export function readsRef(s: State, a: Member, type: RefType, id: string, depth = 0): boolean {
  if (depth > 8) return false;
  if (type === 'plan') { const p = s.plans.find(x => x.id === id); return !!p && readsPlan(s, a, p); }
  if (type === 'expectation') { const e = s.expectations.find(x => x.id === id); return !!e && readsRef(s, a, 'plan', e.planId, depth + 1); }
  if (type === 'meeting') { const m = s.meetings.find(x => x.id === id); return !!m && readsRef(s, a, 'plan', m.planId, depth + 1) && (a.role === 'admin' || m.participantIds.includes(a.id) || manages(s, a, plan(s, m.planId))); }
  if (type === 'feedback') { const f = s.feedback.find(x => x.id === id); return !!f && readsSensitive(s, a, f) && readsRef(s, a, f.sourceType, f.sourceId, depth + 1); }
  if (type === 'review') { const r = s.reviews.find(x => x.id === id); return !!r && readsSensitive(s, a, r); }
  if (type === 'decision') { const d = s.decisions.find(x => x.id === id); return !!d && readsSensitive(s, a, d) && readsRef(s, a, 'review', d.reviewId, depth + 1); }
  const item = s.actions.find(x => x.id === id); return !!item && readsRef(s, a, 'plan', item.planId, depth + 1) && readsRef(s, a, item.sourceType, item.sourceId, depth + 1);
}
export function sourcePlan(s: State, type: RefType, id: string): string { if (type === 'plan') return plan(s, id).id; const group = type === 'expectation' ? s.expectations : type === 'feedback' ? s.feedback : type === 'review' ? s.reviews : type === 'meeting' ? s.meetings : type === 'decision' ? s.decisions : s.actions; const record = group.find(x => x.id === id); ensure(record, 'Originating record not found.', 404); return record.planId; }
export function viewFor(s: State, a: Member): View {
  const plans = s.plans.filter(p => readsPlan(s, a, p)).sort((x, y) => x.createdAt.localeCompare(y.createdAt) || x.title.localeCompare(y.title)); const ids = new Set(plans.map(p => p.id));
  const actions = s.actions.filter(x => readsRef(s, a, 'action', x.id)); const actionIds = new Set(actions.map(x => x.id));
  const feedback = s.feedback.filter(x => readsRef(s, a, 'feedback', x.id)).sort((x, y) => x.createdAt.localeCompare(y.createdAt));
  const reviews = s.reviews.filter(x => readsRef(s, a, 'review', x.id)).map(r => ({ ...r, sheet: { expectationIds: r.sheet.expectationIds.filter(id => readsRef(s, a, 'expectation', id)), feedbackIds: r.sheet.feedbackIds.filter(id => readsRef(s, a, 'feedback', id)), actionIds: r.sheet.actionIds.filter(id => actionIds.has(id)), followUpIds: r.sheet.followUpIds.filter(id => s.followUps.some(f => f.id === id && actionIds.has(f.actionId))) } }));
  const members = s.members.filter(m => a.active && (a.role === 'admin' || m.id === a.id || managesPerson(a, m)));
  const names = new Set([a.id, ...members.map(m => m.id), ...plans.flatMap(p => [p.ownerId, ...p.participantIds]), ...feedback.flatMap(f => [f.authorId, f.recipientId, f.subjectId]), ...reviews.flatMap(r => [r.authorId, r.recipientId, r.subjectId]), ...s.members.filter(m => m.active && plans.some(p => manages(s, m, p))).map(m => m.id)]);
  return { ...s, me: a, members, directory: s.members.filter(m => names.has(m.id)).map(m => ({ id: m.id, name: m.name, jobTitle: m.jobTitle })), plans, expectations: s.expectations.filter(x => ids.has(x.planId)), results: s.results.filter(x => ids.has(x.planId)).sort((x, y) => x.at.localeCompare(y.at)), versions: s.versions.filter(v => ids.has(v.planId) && readsPlan(s, a, v.plan)).sort((x, y) => x.number - y.number), actions, followUps: s.followUps.filter(f => actionIds.has(f.actionId)), feedback, reviews, decisions: s.decisions.filter(x => readsRef(s, a, 'decision', x.id)).sort((x, y) => x.at.localeCompare(y.at)), meetings: s.meetings.filter(x => readsRef(s, a, 'meeting', x.id)), acknowledgements: s.acknowledgements.filter(x => ids.has(x.planId) && (x.userId === a.id || manages(s, a, plan(s, x.planId)))), notifications: s.notifications.filter(x => x.userId === a.id && (!x.planId || ids.has(x.planId))).sort((x, y) => x.createdAt.localeCompare(y.createdAt)), audit: a.role === 'admin' ? [...s.audit].sort((x, y) => x.at.localeCompare(y.at)) : [] };
}
