import { closed, type State, type Member, type Command, type Review } from './model';
import { ensure, member, manages, readsRef } from './policy';
import { text, choice, day, visibility } from './validation';
import { id, notify, editable, newAction, recordVersion } from './transitions';
export function review(s: State, a: Member, c: Command, at: string): string | null { const d = c.payload;
  if (c.type === 'review.schedule') { const p = editable(s, a, text(d, 'planId')); const reviewerId = text(d, 'reviewerId', false, 100) || a.id; const reviewer = member(s, reviewerId); ensure(manages(s, reviewer, p), 'Choose a reviewer with authority over this plan.', 400); const subjectId = text(d, 'subjectId', false, 100) || p.ownerId; ensure(subjectId === p.ownerId || p.participantIds.includes(subjectId), 'Review subject must belong to the plan.', 400); const vis = visibility(d, a); ensure(vis !== 'leadership' || reviewer.role === 'admin', 'Choose an executive reviewer.', 400); const meetingId = id(); const scheduledFor = day(d, 'scheduledFor'); s.meetings.push({ id: meetingId, planId: p.id, title: text(d, 'title', false, 140) || `${p.title} review`, kind: text(d, 'kind', false, 100) || 'Manager / Employee Check-In', cadence: p.cadence, participantIds: [...new Set([reviewerId, subjectId])], agenda: text(d, 'agenda', false) || 'Expectations · KPI exceptions · open feedback · commitments · decisions · next review' }); const r: Review = { id: id(), planId: p.id, meetingId, scheduledFor, authorId: a.id, recipientId: reviewerId, subjectId, visibility: vis, status: 'scheduled', notes: '', outcome: '', nextReview: '', decisionId: '', completedAt: '', sheet: { expectationIds: [], feedbackIds: [], actionIds: [], followUpIds: [] } }; s.reviews.push(r); p.nextReview = scheduledFor; notify(s, reviewerId, p.id, 'A management review is scheduled.', at); notify(s, subjectId, p.id, 'Your next check-in has been scheduled.', at); return r.id; }
  if (c.type !== 'review.complete') return null;
  const r = s.reviews.find(x => x.id === text(d, 'id')); ensure(r, 'Review not found.', 404); const p = editable(s, a, r.planId); ensure(readsRef(s, a, 'review', r.id)); ensure(r.status === 'scheduled', 'This review has already been completed.', 409); const outcome = choice(d, 'outcome', ['no_change', 'update_plan', 'follow_up', 'escalation'] as const); const nextReview = day(d, 'nextReview'); ensure(nextReview > at.slice(0, 10), 'The next review must be after today.', 400); const decisionText = text(d, 'decision'); r.notes = text(d, 'notes', false); r.outcome = outcome; r.status = 'completed'; r.nextReview = nextReview; r.completedAt = at;
  r.sheet = { expectationIds: s.expectations.filter(x => x.planId === p.id).map(x => x.id), feedbackIds: s.feedback.filter(x => x.planId === p.id && x.status !== 'resolved' && readsRef(s, a, 'feedback', x.id)).map(x => x.id), actionIds: s.actions.filter(x => x.planId === p.id && !closed(x.status) && readsRef(s, a, 'action', x.id)).map(x => x.id), followUpIds: s.followUps.filter(x => x.planId === p.id && !closed(x.status) && readsRef(s, a, 'action', x.actionId)).map(x => x.id) };
  const decision = { id: id(), planId: p.id, reviewId: r.id, text: decisionText, outcome, followUpId: '', at, authorId: a.id, recipientId: r.recipientId, subjectId: r.subjectId, visibility: r.visibility }; s.decisions.push(decision); r.decisionId = decision.id;
  p.nextReview = nextReview; p.updatedAt = at;
  if (outcome === 'update_plan') { p.purpose = text(d, 'revisedPurpose'); recordVersion(s, p, text(d, 'changeSummary'), a.id, at); }
  if (outcome === 'follow_up' || outcome === 'escalation') { let ownerId = text(d, 'ownerId', outcome === 'follow_up', 100); if (outcome === 'escalation') { const executive = s.members.find(m => m.active && m.role === 'admin' && m.id !== a.id); ensure(executive, 'Add another authorized executive before escalating. An escalation must have a higher-level recipient.', 409); ownerId = executive.id; } const action = newAction(s, a, p, { ...d, ownerId, description: text(d, 'description'), sourceType: 'decision', sourceId: decision.id }, at, true, outcome === 'escalation'); decision.followUpId = action.followUpId; }
  s.reviews.push({ ...structuredClone(r), id: id(), scheduledFor: nextReview, status: 'scheduled', notes: '', outcome: '', nextReview: '', decisionId: '', completedAt: '', sheet: { expectationIds: [], feedbackIds: [], actionIds: [], followUpIds: [] } }); notify(s, r.subjectId, p.id, 'Review completed. A decision and next check-in are available.', at); return r.id;
}
