import { randomUUID } from 'node:crypto';
import type { State, Member, Plan, RefType, ActionItem } from './model';
import { ensure, plan, member, manages, managesPerson, readsPlan, readsRef, sourcePlan } from './policy';
import { text, day, choice, type Payload } from './validation';
export const id = () => randomUUID();
export function notify(s: State, userId: string, planId: string, message: string, at: string) { s.notifications.push({ id: id(), userId, planId, text: message, createdAt: at, readAt: '' }); }
export function editable(s: State, a: Member, planId: string): Plan { const p = plan(s, planId); ensure(manages(s, a, p)); ensure(p.status !== 'completed', 'This plan is closed. Reopen it before changing its expectations.', 409); return p; }
export function assignable(s: State, a: Member, p: Plan, ownerId: string): Member { const m = member(s, ownerId); ensure(managesPerson(a, m), 'The assignee is outside your management authority.'); ensure(readsPlan(s, m, p), 'The assignee must be an authorized plan participant.', 400); return m; }
export function recordVersion(s: State, p: Plan, summary: string, authorId: string, at: string) { p.version += 1; p.updatedAt = at; const versionId = id(); s.versions.push({ id: versionId, planId: p.id, number: p.version, plan: structuredClone(p), expectations: structuredClone(s.expectations.filter(e => e.planId === p.id)), summary, authorId, at }); for (const userId of new Set([p.ownerId, ...p.participantIds])) if (userId !== authorId) { s.acknowledgements.push({ id: id(), planId: p.id, versionId, userId, acknowledgedAt: '' }); notify(s, userId, p.id, `Plan updated: ${p.title}. Review the new expectations.`, at); } }
export function origin(s: State, a: Member, p: Plan, data: Payload): { sourceType: RefType; sourceId: string } { const sourceType = choice(data, 'sourceType', ['plan', 'expectation', 'feedback', 'review', 'meeting', 'decision', 'action'] as const, 'plan'); const sourceId = text(data, 'sourceId', false, 100) || p.id; ensure(sourcePlan(s, sourceType, sourceId) === p.id, 'The originating record belongs to another plan.', 400); ensure(readsRef(s, a, sourceType, sourceId), 'You cannot access the originating record.'); return { sourceType, sourceId }; }
export function newAction(s: State, a: Member, p: Plan, data: Payload, at: string, followUp: boolean, escalation = false): ActionItem { const ownerId = text(data, 'ownerId', true, 100); const from = origin(s, a, p, data); let owner: Member;
  if (escalation) { owner = member(s, ownerId); ensure(manages(s, a, p) && owner.role === 'admin' && owner.id !== a.id && from.sourceType === 'decision' && s.decisions.some(d => d.id === from.sourceId && d.outcome === 'escalation'), 'Escalations require an authorized executive recipient.'); } else owner = assignable(s, a, p, ownerId);
  ensure(readsRef(s, owner, from.sourceType, from.sourceId), 'The assignee cannot see the source. Assign its authorized reviewer instead.', 400); const kpiId = text(data, 'kpiId', false, 100); if (kpiId) ensure(s.expectations.some(e => e.id === kpiId && e.planId === p.id && e.kind === 'kpi'), 'Select a KPI from this plan.', 400); const action: ActionItem = { id: id(), planId: p.id, description: text(data, 'description'), ownerId, dueDate: day(data, 'dueDate'), priority: choice(data, 'priority', ['low', 'normal', 'high'] as const, 'normal'), status: 'open', ...from, kpiId, followUpId: followUp ? id() : '', evidence: '', createdAt: at, completedAt: '', completedBy: '', verifiedAt: '', verifiedBy: '', history: [{ at, by: a.id, status: 'open', evidence: '' }] }; s.actions.push(action); ensure(readsRef(s, a, 'action', action.id) && readsRef(s, owner, 'action', action.id), 'This source chain is too deep. Link directly to the originating plan, feedback, or decision.', 400); if (followUp) s.followUps.push({ id: action.followUpId, planId: p.id, requirement: action.description, ownerId, dueDate: action.dueDate, nextReview: day(data, 'nextReview', false), ...from, actionId: action.id, status: 'open', evidence: '', completedAt: '', verifiedBy: '' }); if (from.sourceType === 'feedback') { const f = s.feedback.find(f => f.id === from.sourceId)!; f.actionIds.push(action.id); f.status = 'follow_up_required'; f.history.push({ at, by: a.id, text: 'Follow-up assigned.', status: f.status }); } notify(s, ownerId, p.id, followUp ? 'A follow-up needs your action.' : 'A new commitment has been assigned to you.', at); return action; }
