import { closed, feedbackCategories, type State, type Member, type Command } from './model';
import { ensure, plan, member, manages, readsPlan, readsRef } from './policy';
import { text, choice, day, visibility } from './validation';
import { id, notify, editable, newAction, origin } from './transitions';
export function work(s: State, a: Member, c: Command, at: string): string | null { const d = c.payload;
  switch (c.type) {
    case 'action.create':
    case 'followup.create': { const p = editable(s, a, text(d, 'planId')); return newAction(s, a, p, d, at, c.type === 'followup.create').id; }
    case 'action.progress': { const item = s.actions.find(x => x.id === text(d, 'id')); ensure(item, 'Action not found.', 404); ensure(readsRef(s, a, 'action', item.id) && (item.ownerId === a.id || manages(s, a, plan(s, item.planId)))); ensure(!closed(item.status), 'Closed commitments retain their evidence and cannot be overwritten.', 409); const status = choice(d, 'status', ['open', 'in_progress', 'waiting', 'submitted'] as const); const evidence = text(d, 'evidence', status === 'submitted'); item.status = status; item.evidence = evidence; if (status === 'submitted') { item.completedAt = at; item.completedBy = a.id; } item.history.push({ at, by: a.id, status, evidence }); const f = s.followUps.find(x => x.id === item.followUpId); if (f) { f.status = status; f.evidence = evidence; } if (status === 'submitted') { const p = plan(s, item.planId); s.members.filter(m => m.active && manages(s, m, p)).forEach(m => notify(s, m.id, p.id, 'Completion evidence is ready for verification.', at)); } return item.id; }
    case 'action.verify': { const item = s.actions.find(x => x.id === text(d, 'id')); ensure(item, 'Action not found.', 404); ensure(manages(s, a, plan(s, item.planId)) && readsRef(s, a, 'action', item.id)); ensure(item.status === 'submitted' && item.evidence.length > 0, 'Submit completion evidence before verification.', 409); item.status = 'completed'; item.verifiedBy = a.id; item.verifiedAt = at; item.history.push({ at, by: a.id, status: 'completed', evidence: item.evidence }); const f = s.followUps.find(x => x.id === item.followUpId); if (f) { f.status = 'completed'; f.evidence = item.evidence; f.completedAt = at; f.verifiedBy = a.id; } notify(s, item.ownerId, item.planId, 'Your completion evidence has been verified.', at); return item.id; }
    case 'action.cancel': { const item = s.actions.find(x => x.id === text(d, 'id')); ensure(item, 'Action not found.', 404); ensure(manages(s, a, plan(s, item.planId)) && readsRef(s, a, 'action', item.id)); ensure(!closed(item.status), 'This commitment is already closed.', 409); item.status = 'cancelled'; item.history.push({ at, by: a.id, status: 'cancelled', evidence: text(d, 'reason') }); const f = s.followUps.find(x => x.id === item.followUpId); if (f) f.status = 'cancelled'; return item.id; }
    case 'feedback.create': { const p = plan(s, text(d, 'planId')); ensure(readsPlan(s, a, p)); const recipientId = text(d, 'recipientId', true, 100); const recipient = member(s, recipientId); const from = origin(s, a, p, d); ensure(readsPlan(s, recipient, p) && readsRef(s, recipient, from.sourceType, from.sourceId), 'The recipient cannot access this subject.', 400); const subjectId = text(d, 'subjectId', false, 100) || a.id; member(s, subjectId); ensure(subjectId === a.id || manages(s, a, p), 'Submit feedback about yourself or within your management authority.'); const vis = visibility(d, a); if (vis === 'plan') ensure(s.members.filter(m => m.active && readsPlan(s, m, p)).every(m => readsRef(s, m, from.sourceType, from.sourceId)), 'Private source records cannot be exposed through shared feedback.', 400); ensure(vis !== 'leadership' || recipient.role === 'admin', 'Executive-only feedback needs an executive recipient.', 400); const category = choice(d, 'category', feedbackCategories); ensure(category !== 'Manager Feedback' || a.role !== 'employee'); const responseRequired = d.responseRequired === true; const f = { id: id(), planId: p.id, authorId: a.id, recipientId, subjectId, visibility: vis, category, text: text(d, 'text'), ...from, responseRequired, responseDue: day(d, 'responseDue', responseRequired), status: 'submitted' as const, response: '', respondedAt: '', respondedBy: '', actionIds: [] as string[], createdAt: at, history: [{ at, by: a.id, text: 'Submitted.', status: 'submitted' }] }; s.feedback.push(f); notify(s, recipientId, p.id, 'Feedback requires your attention.', at); return f.id; }
    case 'feedback.respond': { const f = s.feedback.find(x => x.id === text(d, 'id')); ensure(f, 'Feedback not found.', 404); ensure(readsRef(s, a, 'feedback', f.id) && (a.id === f.recipientId || manages(s, a, plan(s, f.planId)))); ensure(f.status !== 'resolved', 'Resolved feedback is retained. Submit a new entry to continue the discussion.', 409); const response = text(d, 'response', false); const requested = choice(d, 'status', ['acknowledged', 'reviewed', 'resolved'] as const); if (requested !== 'acknowledged') ensure(response.length > 0, 'A substantive response is required.', 400); if (requested === 'resolved') ensure(f.actionIds.every(actionId => closed(s.actions.find(x => x.id === actionId)?.status || 'open')), 'Complete and verify the linked actions before resolving feedback.', 409); if (response) { f.response = response; f.respondedAt = at; f.respondedBy = a.id; } f.status = requested !== 'resolved' && f.actionIds.some(actionId => !closed(s.actions.find(x => x.id === actionId)?.status || 'open')) ? 'follow_up_required' : requested; f.history.push({ at, by: a.id, text: response || 'Acknowledged.', status: f.status }); notify(s, f.authorId, f.planId, 'There is a response to your feedback.', at); return f.id; }
    case 'acknowledge': { const ack = s.acknowledgements.find(x => x.id === text(d, 'id')); ensure(ack && ack.userId === a.id && readsPlan(s, a, plan(s, ack.planId))); ensure(!ack.acknowledgedAt, 'Already acknowledged.', 409); ack.acknowledgedAt = at; return ack.id; }
    case 'notification.read': { const n = s.notifications.find(x => x.id === text(d, 'id')); ensure(n && n.userId === a.id); n.readAt = at; return n.id; }
    default: return null;
  }
}
