import { test, expect, type Page } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { seed, password } from '../emulator';
import { fixture, person, alicePlan } from '../fixture';
const s = fixture();
const alice = person(s, 'alice'); const manager = person(s, 'manager'); const p = alicePlan(s);
const future = new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10);
async function login(page: Page, who: string) { await page.goto('/'); await page.getByLabel('Email address').fill(`${who}@example.test`); await page.getByLabel('Password', { exact: true }).fill(password); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible(); }
async function save(page: Page, name = 'Save changes') { await page.getByRole('dialog').getByRole('button', { name, exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); }
async function openPlan(page: Page, title = p.title) { await page.getByRole('navigation').getByRole('button', { name: 'Management Plans', exact: true }).click(); await page.getByRole('button').filter({ has: page.getByRole('heading', { name: title, exact: true }) }).click(); await expect(page.getByRole('heading', { level: 1, name: title })).toBeVisible(); }
test.beforeAll(async () => { await seed(s); mkdirSync('evidence', { recursive: true }); });
test('The organization completes a private management cycle on desktop and mobile', async ({ browser }) => {
  const errors: string[] = [];
  const executiveContext = await browser.newContext(); const executive = await executiveContext.newPage(); executive.on('pageerror', e => errors.push(e.message));
  await login(executive, 'admin'); await executive.getByRole('button', { name: '+ Create a plan', exact: true }).click();
  await executive.getByLabel('Plan name', { exact: false }).fill('Sprint operating plan'); await executive.getByLabel('Purpose / intended result', { exact: false }).fill('Make management expectations explicit and close every follow-up.'); await executive.getByLabel('Owner', { exact: false }).selectOption(alice.id); await save(executive);
  await openPlan(executive, 'Sprint operating plan'); await executive.getByRole('button', { name: '+ Define expectation', exact: true }).click(); await executive.getByLabel('Expectation type', { exact: false }).selectOption('kpi'); await executive.getByLabel('Expectation', { exact: true }).fill('Weekly qualified opportunities'); await executive.getByLabel('Measurement method / unit', { exact: false }).fill('Qualified opportunities recorded'); await executive.getByLabel('Target / success definition', { exact: false }).fill('10 per week'); await save(executive);
  const employeeContext = await browser.newContext(); const employee = await employeeContext.newPage(); employee.on('pageerror', e => errors.push(e.message)); await login(employee, 'alice');
  await expect(employee.getByRole('heading', { name: 'My plan. My next steps.' })).toBeVisible(); await expect(employee.getByRole('heading', { name: 'Weekly qualified opportunities', exact: true })).toBeVisible();
  await employee.locator('.expectation-card').filter({ hasText: 'Weekly qualified opportunities' }).getByRole('button', { name: 'Update progress' }).click(); await employee.getByLabel('Current result', { exact: false }).fill('7 opportunities'); await employee.getByLabel('Progress (%)', { exact: false }).fill('70'); await employee.getByLabel('Current status', { exact: false }).selectOption('at_risk'); await save(employee);
  await openPlan(employee, 'Sprint operating plan'); await employee.locator('.heading-actions').getByRole('button', { name: 'Give feedback', exact: true }).click(); await employee.getByLabel('Recipient', { exact: false }).selectOption(manager.id); await employee.getByLabel('Feedback type', { exact: false }).selectOption('Concern / Blocker'); await employee.getByLabel('Feedback', { exact: true }).fill('Need access to the institutional lead list.'); await save(employee);
  const managerContext = await browser.newContext(); const leader = await managerContext.newPage(); leader.on('pageerror', e => errors.push(e.message)); await login(leader, 'manager'); await openPlan(leader, 'Sprint operating plan'); await leader.getByRole('button', { name: 'Feedback', exact: true }).click(); await leader.getByRole('button', { name: 'Respond / resolve' }).click(); await leader.getByLabel('Your response', { exact: false }).fill('I will arrange access and verify completion.'); await save(leader);
  await leader.getByRole('button', { name: 'Create follow-up →' }).click(); await leader.getByLabel('Required action', { exact: false }).fill('Provide and confirm lead-list access.'); await leader.getByLabel('Owner', { exact: true }).selectOption(alice.id); await save(leader);
  await leader.getByRole('button', { name: 'Reviews', exact: true }).click(); await leader.getByRole('button', { name: '+ Schedule review' }).click(); await save(leader);
  await leader.getByRole('button', { name: 'Open review sheet' }).click(); await expect(leader.getByRole('dialog').getByText('Need access to the institutional lead list.', { exact: false })).toBeVisible(); await expect(leader.getByRole('dialog').getByText('7 opportunities', { exact: false })).toBeVisible(); await leader.getByLabel('Management decision / rationale', { exact: false }).fill('Continue the current target; lead-list access remains the explicit follow-up.'); await leader.getByLabel('Next review date', { exact: false }).fill(future); await save(leader, 'Record decision & continue');
  await employee.reload(); await employee.getByRole('navigation').getByRole('button', { name: 'Follow-Up', exact: false }).click(); await employee.locator('.commitment').filter({ hasText: 'Provide and confirm lead-list access.' }).getByRole('button', { name: 'Update', exact: true }).click(); await employee.getByLabel('Progress status', { exact: false }).selectOption('submitted'); await employee.getByLabel('Completion evidence / progress note', { exact: false }).fill('Access confirmed. Reference LEAD-2026-001; list reviewed and usable.'); await save(employee);
  await leader.reload(); await leader.getByRole('navigation').getByRole('button', { name: 'Follow-Up', exact: false }).click(); await leader.getByRole('button', { name: 'Review evidence & verify →' }).click(); await expect(leader.getByRole('dialog').getByText('LEAD-2026-001', { exact: false }).first()).toBeVisible(); await save(leader, 'Verify completion');
  await openPlan(leader, 'Sprint operating plan'); await leader.getByRole('button', { name: 'Feedback', exact: true }).click(); await leader.getByRole('button', { name: 'Respond / resolve' }).click(); await leader.getByLabel('Your response', { exact: false }).fill('Access verified against LEAD-2026-001. Blocker resolved.'); await leader.getByLabel('Disposition', { exact: false }).selectOption('resolved'); await save(leader); await expect(leader.locator('.feedback-card').getByText('Resolved', { exact: true })).toBeVisible();
  await leader.getByRole('button', { name: 'Expectations', exact: true }).click(); await leader.getByRole('button', { name: 'Revise', exact: true }).click(); await leader.getByLabel('Target / success definition', { exact: false }).fill('12 per week'); await leader.getByLabel('Change summary', { exact: false }).fill('Target increased for the next management period.'); await save(leader); await leader.getByRole('button', { name: 'History', exact: true }).click(); await expect(leader.getByText('Version 3', { exact: true })).toBeVisible();
  await leader.getByRole('navigation').getByRole('button', { name: 'Overview', exact: true }).click(); await leader.screenshot({ path: 'evidence/leadership-desktop.png', fullPage: true });
  await employee.reload(); await expect(employee.getByRole('heading', { name: 'My plan. My next steps.' })).toBeVisible(); await employee.setViewportSize({ width: 390, height: 844 }); await employee.screenshot({ path: 'evidence/employee-mobile.png', fullPage: true }); expect(await employee.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true); await expect(employee.getByRole('heading', { name: 'What do I need to do now?' })).toBeVisible();
  await executive.reload(); await executive.getByRole('navigation').getByRole('button', { name: 'Administration', exact: true }).click(); await executive.screenshot({ path: 'evidence/administration-desktop.png', fullPage: true });
  expect(errors).toEqual([]); await executiveContext.close(); await employeeContext.close(); await managerContext.close();
});
test('A peer cannot retrieve another employee’s protected plan', async ({ page }) => { await login(page, 'bob'); await expect(page.getByText('Sprint operating plan', { exact: true })).toHaveCount(0); await expect(page.getByText('Need access to the institutional lead list.', { exact: true })).toHaveCount(0); await expect(page.getByRole('button', { name: 'Administration', exact: true })).toHaveCount(0); });
