import { closed, type State, type Member, type Plan, type Command } from './model';
import { DomainError, ensure, plan, member, manages, managesPerson, readsPlan } from './policy';
import { text, choice, day, numeric, ids } from './validation';
import { id, notify, editable, assignable, recordVersion } from './transitions';
export function administer(s: State, a: Member, c: Command, at: string): string | null { const d = c.payload;
  switch (c.type) {
    case 'team.create': { ensure(a.role === 'admin'); const team = { id: id(), name: text(d, 'name', true, 100) }; s.teams.push(team); return team.id; }
    case 'organization.update': { ensure(a.role === 'admin'); s.organization.name = text(d, 'name', true, 120); const timezone = text(d, 'timezone', true, 80); try { new Intl.DateTimeFormat('en-US', { timeZone: timezone }); } catch { throw new DomainError('Choose a valid IANA timezone.'); } s.organization.timezone = timezone; return s.organization.id; }
    case 'member.save': { ensure(a.role === 'admin'); const email = text(d, 'email', true, 254).toLowerCase(); ensure(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email), 'Enter a valid email.', 400); const role = choice(d, 'role', ['admin', 'manager', 'employee'] as const); const teamId = text(d, 'teamId', false, 100); ensure(!teamId || s.teams.some(t => t.id === teamId), 'Choose an existing function.', 400); ensure(role !== 'manager' || teamId, 'Managers need a function to define their authority.', 400); const existing = s.members.find(m => m.email === email); const active = d.active !== false; if (existing?.role === 'admin' && (!active || role !== 'admin')) ensure(s.members.some(m => m.id !== existing.id && m.role === 'admin' && m.active), 'Keep at least one active administrator.', 400); if (existing) { Object.assign(existing, { name: text(d, 'name', true, 100), jobTitle: text(d, 'jobTitle', false, 120), role, teamId, active }); return existing.id; } ensure(s.members.length < 75, 'The sprint release supports up to 75 people.', 409); const m: Member = { id: id(), uid: '', email, name: text(d, 'name', true, 100), jobTitle: text(d, 'jobTitle', false, 120), role, teamId, active }; s.members.push(m); return m.id; }
    case 'plan.create': { ensure(a.role !== 'employee'); ensure(s.plans.length < 50, 'The sprint release supports up to 50 plans.', 409); const ownerId = text(d, 'ownerId', true, 100); const owner = member(s, ownerId); ensure(managesPerson(a, owner)); const scope = choice(d, 'scope', ['organization', 'function', 'individual'] as const); ensure(scope !== 'organization' || a.role === 'admin'); const pv = choice(d, 'visibility', ['participants', 'organization', 'leadership'] as const, 'participants'); ensure(pv !== 'leadership' || a.role === 'admin'); ensure(pv !== 'organization' || (scope === 'organization' && a.role === 'admin'), 'Only organizational plans can be shared with the whole organization.', 400); const participantIds = [...new Set([ownerId, ...ids(d, 'participantIds')])]; ensure(scope !== 'individual' || participantIds.every(x => x === ownerId), 'An individual plan has one employee subject. Managers have scoped access automatically.', 400); for (const personId of participantIds) ensure(managesPerson(a, member(s, personId))); const p: Plan = { id: id(), title: text(d, 'title', true, 140), purpose: text(d, 'purpose'), horizon: text(d, 'horizon', true, 100), scope, ownerId, participantIds, teamId: owner.teamId, visibility: pv, cadence: text(d, 'cadence', true, 100), nextReview: day(d, 'nextReview'), status: 'active', version: 0, createdAt: at, updatedAt: at }; ensure(participantIds.every(personId => readsPlan(s, member(s, personId), p)), 'Every plan participant must be able to read the plan. Executive-only plans require executive participants.', 400); s.plans.push(p); recordVersion(s, p, 'Plan established.', a.id, at); return p.id; }
    case 'plan.revise': { const p = plan(s, text(d, 'planId')); ensure(manages(s, a, p)); p.title = text(d, 'title', true, 140); p.purpose = text(d, 'purpose'); p.horizon = text(d, 'horizon', true, 100); p.cadence = text(d, 'cadence', true, 100); p.nextReview = day(d, 'nextReview'); p.status = choice(d, 'status', ['active', 'at_risk', 'completed'] as const, p.status); if (p.status === 'completed') { ensure(!s.actions.some(x => x.planId === p.id && !closed(x.status)) && !s.feedback.some(x => x.planId === p.id && x.status !== 'resolved'), 'Resolve commitments and feedback before closing this plan.', 409); const reason = text(d, 'summary'); for (const r of s.reviews.filter(r => r.planId === p.id && r.status === 'scheduled')) { r.status = 'cancelled'; r.cancelledAt = at; r.cancelledBy = a.id; r.cancellationReason = `Plan closed: ${reason}`; s.audit.push({ id: id(), at, actorId: a.id, type: 'review.cancelled', targetId: r.id, summary: r.cancellationReason }); notify(s, r.subjectId, p.id, 'The plan is closed. Its remaining scheduled review has been cancelled and retained in history.', at); } p.nextReview = ''; } recordVersion(s, p, text(d, 'summary'), a.id, at); return p.id; }
    case 'expectation.save': { const p = editable(s, a, text(d, 'planId')); const ownerId = text(d, 'ownerId', true, 100); assignable(s, a, p, ownerId); const expectationId = text(d, 'id', false, 100); let e = s.expectations.find(e => e.id === expectationId && e.planId === p.id); ensure(!expectationId || e, 'Expectation not found.', 404); const fields = { title: text(d, 'title', true, 160), description: text(d, 'description', false), ownerId, measure: text(d, 'measure', true, 500), target: text(d, 'target', true, 300), frequency: text(d, 'frequency', true, 100), updatedAt: at }; if (e) Object.assign(e, fields); else { e = { id: id(), planId: p.id, kind: choice(d, 'kind', ['responsibility', 'goal', 'kpi'] as const), ...fields, result: '', progress: 0, status: 'on_track' }; s.expectations.push(e); } recordVersion(s, p, text(d, 'summary', false) || `Defined expectation: ${e.title}.`, a.id, at); notify(s, ownerId, p.id, 'An expectation has been assigned or revised.', at); return e.id; }
    case 'expectation.progress': { const e = s.expectations.find(e => e.id === text(d, 'id')); ensure(e, 'Expectation not found.', 404); const p = plan(s, e.planId); ensure(readsPlan(s, a, p) && (e.ownerId === a.id || manages(s, a, p))); ensure(p.status !== 'completed', 'This plan is closed.', 409); e.result = text(d, 'result', true, 500); e.progress = numeric(d, 'progress', e.progress); e.status = choice(d, 'status', ['on_track', 'at_risk', 'blocked', 'complete'] as const); e.updatedAt = at; s.results.push({ id: id(), expectationId: e.id, planId: p.id, result: e.result, note: text(d, 'note', false), status: e.status, authorId: a.id, at }); return e.id; }
    default: return null;
  }
}
