import { describe, expect, it } from 'vitest';
import { execute } from '../lib/domain';
import { readsPlan, readsRef, viewFor } from '../lib/policy';
import { overdue, todayInZone, type State } from '../lib/model';
import { fixture, person, alicePlan, testTime } from './fixture';
function apply(s: State, who: string, type: string, payload: Record<string, unknown>, at = testTime) { return execute(s, person(s, who).id, { type, payload }, at); }
function expectation(s: State) { return apply(s, 'manager', 'expectation.save', { planId: alicePlan(s).id, kind: 'kpi', title: 'Weekly completed requests', ownerId: person(s, 'alice').id, measure: 'Service requests completed', target: '10', frequency: 'Weekly' }); }
function feedback(s: State) { return apply(s, 'alice', 'feedback.create', { planId: alicePlan(s).id, recipientId: person(s, 'manager').id, category: 'Concern / Blocker', text: 'Supplier approval is missing.', visibility: 'private', responseRequired: true, responseDue: '2026-09-10' }); }
function follow(s: State) { return apply(s, 'manager', 'followup.create', { planId: alicePlan(s).id, ownerId: person(s, 'alice').id, description: 'Obtain supplier approval.', dueDate: '2026-09-11', sourceType: 'feedback', sourceId: s.feedback[0].id }); }
function schedule(s: State) { return apply(s, 'manager', 'review.schedule', { planId: alicePlan(s).id, scheduledFor: '2026-09-07', visibility: 'private' }); }
describe('Authority is enforced independently of the interface', () => {
  it('projects only the employee’s plans, not another employee’s private records', () => { const s = fixture(); const alice = person(s, 'alice'); expect(readsPlan(s, alice, alicePlan(s))).toBe(true); const v = viewFor(s, alice); expect(v.plans).toHaveLength(1); expect(JSON.stringify(v)).not.toContain('Private Bob expectations'); expect(v.audit).toEqual([]); expect(v.members).toHaveLength(1); });
  it('allows the in-scope manager, but rejects another function', () => { const s = fixture(); expect(() => apply(s, 'manager', 'expectation.save', { planId: alicePlan(s).id, kind: 'goal', title: 'Reliable service', ownerId: person(s, 'alice').id, target: '95%', measure: 'On-time delivery', frequency: 'Weekly' })).not.toThrow(); expect(() => apply(s, 'outsider', 'expectation.save', { planId: alicePlan(s).id })).toThrow(); });
  it('prevents employees from granting roles or modifying plans', () => { const s = fixture(); expect(() => apply(s, 'alice', 'member.save', { email: 'alice@example.test', role: 'admin' })).toThrow(); expect(() => apply(s, 'alice', 'plan.revise', { planId: alicePlan(s).id })).toThrow(); expect(() => apply(s, 'alice', 'team.create', { name: 'Unauthorized' })).toThrow(); });
  it('prevents managers from editing executive access and organizational plans', () => { const s = fixture(); expect(() => apply(s, 'manager', 'member.save', { email: 'test@example.test', role: 'admin' })).toThrow(); expect(() => apply(s, 'manager', 'plan.create', { scope: 'organization', ownerId: person(s, 'manager').id })).toThrow(); });
  it('denies inactive members', () => { const s = fixture(); person(s, 'alice').active = false; expect(() => apply(s, 'alice', 'feedback.create', {})).toThrow(); expect(viewFor(s, person(s, 'alice')).plans).toEqual([]); });
  it('does not share an individual plan with peer participants', () => { const s = fixture(); expect(() => apply(s, 'manager', 'plan.create', { ownerId: person(s, 'alice').id, participantIds: [person(s, 'bob').id], scope: 'individual', visibility: 'participants' })).toThrow('one employee subject'); });
  it('keeps the last administrator active', () => { const s = fixture(); expect(() => apply(s, 'admin', 'member.save', { email: 'admin@example.test', name: 'Alex', role: 'employee', active: true })).toThrow('at least one'); });
  it('never lets an employee impersonate Manager Feedback', () => { const s = fixture(); expect(() => apply(s, 'alice', 'feedback.create', { planId: alicePlan(s).id, recipientId: person(s, 'manager').id, category: 'Manager Feedback', text: 'Impersonation', visibility: 'private' })).toThrow(); });
});
describe('Expectations and history', () => {
  it('requires a named owner, explicit measure, target, and frequency', () => { const s = fixture(); expect(() => apply(s, 'manager', 'expectation.save', { planId: alicePlan(s).id, ownerId: person(s, 'alice').id, kind: 'goal', title: 'Unmeasured goal' })).toThrow(); });
  it('records progress without allowing silent expectation changes', () => { let s = expectation(fixture()); const old = structuredClone(s); const e = s.expectations[0]; s = apply(s, 'alice', 'expectation.progress', { id: e.id, result: '7', progress: 70, status: 'at_risk', note: 'Awaiting approval.', target: '7', ownerId: person(s, 'alice').id }); expect(s.expectations[0].target).toBe('10'); expect(s.results).toHaveLength(1); expect(s.results[0].authorId).toBe(person(s, 'alice').id); expect(s.versions).toEqual(old.versions); expect(old.expectations[0].result).toBe(''); });
  it('preserves full prior expectations after a material revision', () => { let s = expectation(fixture()); const e = s.expectations[0]; const before = s.versions.find(v => v.planId === e.planId && v.number === 2)!; s = apply(s, 'manager', 'expectation.save', { ...e, target: '12', summary: 'Next cycle target increased.' }, '2026-09-08T16:00:00.000Z'); expect(before.expectations[0].target).toBe('10'); expect(s.versions.find(v => v.id === before.id)?.expectations[0].target).toBe('10'); expect(alicePlan(s).version).toBe(3); expect(s.expectations[0].target).toBe('12'); });
  it('requires acknowledgement by the actual employee, once only', () => { let s = fixture(); const ack = s.acknowledgements.find(a => a.userId === person(s, 'alice').id)!; expect(() => apply(s, 'bob', 'acknowledge', { id: ack.id })).toThrow(); s = apply(s, 'alice', 'acknowledge', { id: ack.id }); expect(s.acknowledgements.find(a => a.id === ack.id)?.acknowledgedAt).toBe(testTime); expect(() => apply(s, 'alice', 'acknowledge', { id: ack.id })).toThrow('Already acknowledged'); });
  it('uses server-supplied timestamps instead of client timestamps', () => { let s = expectation(fixture()); s = apply(s, 'alice', 'expectation.progress', { id: s.expectations[0].id, result: '8', status: 'on_track', at: '1990-01-01' }); expect(s.results[0].at).toBe(testTime); });
  it('rejects invalid calendar dates and unbounded progress', () => { let s = fixture(); expect(() => apply(s, 'manager', 'action.create', { planId: alicePlan(s).id, description: 'Invalid date', ownerId: person(s, 'alice').id, dueDate: '2026-02-30' })).toThrow('valid'); s = expectation(s); expect(() => apply(s, 'alice', 'expectation.progress', { id: s.expectations[0].id, result: '1', status: 'on_track', progress: 101 })).toThrow('between 0 and 100'); });
});
describe('Feedback and follow-through', () => {
  it('requires a response deadline when a response is requested', () => { const s = fixture(); expect(() => apply(s, 'alice', 'feedback.create', { planId: alicePlan(s).id, recipientId: person(s, 'manager').id, category: 'Question', text: 'When?', responseRequired: true })).toThrow('responseDue'); });
  it('does not resolve feedback just because it was acknowledged', () => { let s = feedback(fixture()); s = apply(s, 'manager', 'feedback.respond', { id: s.feedback[0].id, status: 'acknowledged' }); expect(s.feedback[0].status).toBe('acknowledged'); expect(s.feedback[0].respondedAt).toBe(''); });
  it('requires a substantive reply for resolution', () => { const s = feedback(fixture()); expect(() => apply(s, 'manager', 'feedback.respond', { id: s.feedback[0].id, status: 'resolved', response: ' ' })).toThrow('substantive'); });
  it('keeps feedback open while its follow-up is unverified', () => { let s = follow(feedback(fixture())); expect(s.actions[0].followUpId).toBe(s.followUps[0].id); expect(s.followUps[0].actionId).toBe(s.actions[0].id); expect(s.followUps[0].sourceId).toBe(s.feedback[0].id); s = apply(s, 'alice', 'action.progress', { id: s.actions[0].id, status: 'submitted', evidence: 'Approval reference SUP-123.' }); expect(() => apply(s, 'manager', 'feedback.respond', { id: s.feedback[0].id, status: 'resolved', response: 'Done.' })).toThrow('verify'); });
  it('requires evidence and manager authority for closure, then preserves both', () => { let s = follow(feedback(fixture())); const actionId = s.actions[0].id; expect(() => apply(s, 'alice', 'action.progress', { id: actionId, status: 'submitted', evidence: '' })).toThrow(); s = apply(s, 'alice', 'action.progress', { id: actionId, status: 'submitted', evidence: 'Approval reference SUP-123.' }); expect(() => apply(s, 'alice', 'action.verify', { id: actionId })).toThrow(); s = apply(s, 'manager', 'action.verify', { id: actionId }); expect(s.actions[0].status).toBe('completed'); expect(s.actions[0].completedBy).toBe(person(s, 'alice').id); expect(s.actions[0].verifiedBy).toBe(person(s, 'manager').id); expect(s.actions[0].verifiedAt).toBe(testTime); expect(s.followUps[0].status).toBe('completed'); expect(s.followUps[0].evidence).toContain('SUP-123'); expect(() => apply(s, 'manager', 'action.progress', { id: actionId, status: 'open' })).toThrow('cannot be overwritten'); s = apply(s, 'manager', 'feedback.respond', { id: s.feedback[0].id, status: 'resolved', response: 'Evidence verified.' }); expect(s.feedback[0].status).toBe('resolved'); });
  it('rejects another employee updating the action', () => { const s = follow(feedback(fixture())); expect(() => apply(s, 'bob', 'action.progress', { id: s.actions[0].id, status: 'submitted', evidence: 'Forged' })).toThrow(); });
  it('retains cancellation rationale and refuses employee cancellation', () => { let s = follow(feedback(fixture())); expect(() => apply(s, 'alice', 'action.cancel', { id: s.actions[0].id, reason: 'Skip' })).toThrow(); s = apply(s, 'manager', 'action.cancel', { id: s.actions[0].id, reason: 'Superseded by a verified supplier route.' }); expect(s.actions[0].history.at(-1)?.evidence).toContain('Superseded'); expect(s.followUps[0].status).toBe('cancelled'); });
  it('denies cross-plan links', () => { const s = fixture(); expect(() => apply(s, 'manager', 'followup.create', { planId: alicePlan(s).id, sourceType: 'plan', sourceId: s.plans.find(p => p.id !== alicePlan(s).id)!.id, ownerId: person(s, 'alice').id, description: 'Wrong source', dueDate: '2026-09-10' })).toThrow('another plan'); });
  it('does not expose private feedback or its follow-up to a peer on a shared plan', () => { let s = fixture(); s = apply(s, 'manager', 'plan.create', { title: 'Shared function', purpose: 'Shared expectations', horizon: 'Quarterly', cadence: 'Weekly', nextReview: '2026-09-14', scope: 'function', ownerId: person(s, 'manager').id, participantIds: [person(s, 'alice').id, person(s, 'bob').id] }); const p = s.plans.at(-1)!; s = apply(s, 'alice', 'feedback.create', { planId: p.id, recipientId: person(s, 'manager').id, text: 'PRIVATE ALICE DETAIL', category: 'Support Needed', visibility: 'private' }); const f = s.feedback.at(-1)!; expect(readsRef(s, person(s, 'bob'), 'feedback', f.id)).toBe(false); expect(() => apply(s, 'manager', 'feedback.create', { planId: p.id, sourceType: 'feedback', sourceId: f.id, recipientId: person(s, 'alice').id, text: 'Attempt to broaden', category: 'Question', visibility: 'plan' })).toThrow('cannot be exposed'); expect(() => apply(s, 'manager', 'followup.create', { planId: p.id, sourceType: 'feedback', sourceId: f.id, ownerId: person(s, 'bob').id, description: 'Leak to Bob', dueDate: '2026-09-10' })).toThrow('cannot see the source'); s = apply(s, 'manager', 'followup.create', { planId: p.id, sourceType: 'feedback', sourceId: f.id, ownerId: person(s, 'alice').id, description: 'PRIVATE FOLLOW-UP', dueDate: '2026-09-10' }); const bobView = JSON.stringify(viewFor(s, person(s, 'bob'))); expect(bobView).not.toContain('PRIVATE ALICE DETAIL'); expect(bobView).not.toContain('PRIVATE FOLLOW-UP'); });
});
describe('Reviews always continue the management cycle', () => {
  it('records no-change rationale and creates the next review', () => { let s = schedule(expectation(feedback(fixture()))); const reviewId = s.reviews[0].id; s = apply(s, 'manager', 'review.complete', { id: reviewId, outcome: 'no_change', decision: 'Continue existing targets.', nextReview: '2026-09-14' }); expect(s.reviews[0].status).toBe('completed'); expect(s.decisions[0].reviewId).toBe(reviewId); expect(s.reviews[0].sheet.expectationIds).toHaveLength(1); expect(s.reviews[0].sheet.feedbackIds).toHaveLength(1); expect(s.reviews[1].status).toBe('scheduled'); expect(s.reviews[1].scheduledFor).toBe('2026-09-14'); expect(() => apply(s, 'manager', 'review.complete', { id: reviewId })).toThrow('already been completed'); });
  it('cannot complete a review without a decision and next review', () => { const s = schedule(fixture()); expect(() => apply(s, 'manager', 'review.complete', { id: s.reviews[0].id, outcome: 'no_change', nextReview: '2026-09-14' })).toThrow('decision'); expect(() => apply(s, 'manager', 'review.complete', { id: s.reviews[0].id, outcome: 'no_change', decision: 'Continue', nextReview: '2026-09-07' })).toThrow('after today'); });
  it('atomically creates decision, follow-up, and action', () => { let s = schedule(fixture()); s = apply(s, 'manager', 'review.complete', { id: s.reviews[0].id, outcome: 'follow_up', decision: 'Resolve the blocker.', ownerId: person(s, 'alice').id, description: 'Get supplier confirmation.', dueDate: '2026-09-10', nextReview: '2026-09-14' }); expect(s.decisions[0].followUpId).toBe(s.followUps[0].id); expect(s.actions[0].sourceType).toBe('decision'); expect(s.followUps[0].sourceId).toBe(s.decisions[0].id); });
  it('leaves the original state untouched when any part of closure fails', () => { const s = schedule(fixture()); const before = JSON.stringify(s); expect(() => apply(s, 'manager', 'review.complete', { id: s.reviews[0].id, outcome: 'follow_up', decision: 'Resolve', description: 'Missing owner', dueDate: '2026-09-10', nextReview: '2026-09-14' })).toThrow(); expect(JSON.stringify(s)).toBe(before); });
  it('requires and preserves material changes for an update-plan outcome', () => { let s = schedule(fixture()); const old = alicePlan(s).purpose; s = apply(s, 'manager', 'review.complete', { id: s.reviews[0].id, outcome: 'update_plan', decision: 'Prioritize reliability.', revisedPurpose: 'New next-cycle expectations.', changeSummary: 'Shift priorities for the next period.', nextReview: '2026-09-14' }); expect(alicePlan(s).purpose).toBe('New next-cycle expectations.'); expect(s.versions.find(v => v.planId === alicePlan(s).id && v.number === 1)?.plan.purpose).toBe(old); });
  it('routes escalation only to a distinct authorized executive', () => { let s = schedule(fixture()); s = apply(s, 'manager', 'review.complete', { id: s.reviews[0].id, outcome: 'escalation', decision: 'Executive decision needed.', description: 'Confirm budget authority.', dueDate: '2026-09-10', nextReview: '2026-09-14' }); expect(s.actions[0].ownerId).toBe(person(s, 'admin').id); expect(s.followUps[0].status).toBe('open'); });
  it('rejects employee review completion and private peer review reads', () => { const s = schedule(fixture()); expect(() => apply(s, 'alice', 'review.complete', { id: s.reviews[0].id })).toThrow(); expect(readsRef(s, person(s, 'bob'), 'review', s.reviews[0].id)).toBe(false); });
});
describe('Derived reminders and notification ownership', () => {
  it('calculates overdue without destructively changing status', () => { expect(overdue('waiting', '2026-09-06', '2026-09-07')).toBe(true); expect(overdue('completed', '2026-09-06', '2026-09-07')).toBe(false); expect(overdue('open', '2026-09-07', '2026-09-07')).toBe(false); });
  it('uses the configured timezone at a UTC day boundary', () => { expect(todayInZone('America/New_York', new Date('2026-09-08T00:30:00Z'))).toBe('2026-09-07'); });
  it('prevents marking another person’s notification read', () => { const s = feedback(fixture()); const notification = s.notifications.find(n => n.userId === person(s, 'manager').id)!; expect(() => apply(s, 'alice', 'notification.read', { id: notification.id })).toThrow(); });
});
