import { describe, expect, it } from 'vitest';
import { execute } from '../lib/domain';
import { viewFor } from '../lib/policy';
import { fixture, person, alicePlan, testTime } from './fixture';
import type { State } from '../lib/model';
const apply = (s: State, who: string, type: string, payload: Record<string, unknown>, at = testTime) => execute(s, person(s, who).id, { type, payload }, at);
describe('Sprint hardening regressions', () => {
  it('can close a reviewed plan without leaving an unfinishable recurring review', () => { let s = fixture(); s = apply(s, 'manager', 'review.schedule', { planId: alicePlan(s).id, scheduledFor: '2026-09-07' }); s = apply(s, 'manager', 'review.complete', { id: s.reviews[0].id, outcome: 'no_change', decision: 'Continue this cycle.', nextReview: '2026-09-14' }); const p = alicePlan(s); s = apply(s, 'manager', 'plan.revise', { ...p, planId: p.id, status: 'completed', summary: 'All expectations fulfilled. Close the plan.' }); expect(s.reviews.filter(r => r.status === 'scheduled')).toHaveLength(0); expect(s.reviews.filter(r => r.status === 'cancelled')).toHaveLength(1); const v = viewFor(s, person(s, 'alice')); expect(v.reviews).toHaveLength(1); expect(v.archivedReviews).toHaveLength(1); expect(v.archivedReviews[0].cancelledBy).toBe(person(s, 'manager').id); expect(alicePlan(s).nextReview).toBe(''); expect(s.audit.some(a => a.type === 'review.cancelled')).toBe(true); });
  it('does not close a plan with unresolved commitments', () => { let s = fixture(); const p = alicePlan(s); s = apply(s, 'manager', 'action.create', { planId: p.id, ownerId: person(s, 'alice').id, description: 'Unfinished requirement', dueDate: '2026-09-14' }); expect(() => apply(s, 'manager', 'plan.revise', { ...p, planId: p.id, status: 'completed', summary: 'Attempt premature closure.' })).toThrow('Resolve commitments'); });
  it('offers the employee their authorized manager as a feedback recipient before any review exists', () => { const s = fixture(); const v = viewFor(s, person(s, 'alice')); expect(v.directory.some(m => m.id === person(s, 'manager').id)).toBe(true); expect(v.directory.some(m => m.id === person(s, 'bob').id)).toBe(false); });
  it('keeps disabled member entries visible to administrators for reactivation', () => { const s = fixture(); person(s, 'bob').active = false; expect(viewFor(s, person(s, 'admin')).members.some(m => m.id === person(s, 'bob').id)).toBe(true); expect(viewFor(s, person(s, 'manager')).members.some(m => m.id === person(s, 'bob').id)).toBe(false); });
  it('does not let management attach another function’s person as the subject of private feedback', () => { const s = fixture(); expect(() => apply(s, 'manager', 'feedback.create', { planId: alicePlan(s).id, recipientId: person(s, 'manager').id, subjectId: person(s, 'outsider').id, category: 'Manager Feedback', text: 'Wrong management scope', visibility: 'private' })).toThrow('management scope'); });
  it('prevents assigning an executive-only plan to a person who cannot read it', () => { const s = fixture(); expect(() => apply(s, 'admin', 'plan.create', { ownerId: person(s, 'alice').id, scope: 'individual', title: 'Invisible plan', purpose: 'Must not be allowed', horizon: 'Quarterly', cadence: 'Weekly', nextReview: '2026-09-14', visibility: 'leadership' })).toThrow('Every plan participant'); });
  it('uses the organization date when requiring the next review to be in the future', () => { let s = fixture(); s = apply(s, 'manager', 'review.schedule', { planId: alicePlan(s).id, scheduledFor: '2026-09-07' }); s = apply(s, 'manager', 'review.complete', { id: s.reviews[0].id, outcome: 'no_change', decision: 'Continue tomorrow local time.', nextReview: '2026-09-08' }, '2026-09-08T00:30:00.000Z'); expect(s.reviews[0].status).toBe('completed'); });
  it('redacts private feedback IDs from a shared review sheet', () => { let s = fixture(); s = apply(s, 'manager', 'plan.create', { ownerId: person(s, 'manager').id, participantIds: [person(s, 'alice').id, person(s, 'bob').id], scope: 'function', title: 'Shared team plan', purpose: 'Shared work', horizon: 'Quarterly', cadence: 'Weekly', nextReview: '2026-09-14' }); const p = s.plans.at(-1)!; s = apply(s, 'alice', 'feedback.create', { planId: p.id, recipientId: person(s, 'manager').id, category: 'Support Needed', text: 'PRIVATE RECORD', visibility: 'private' }); const feedbackId = s.feedback[0].id; s = apply(s, 'manager', 'review.schedule', { planId: p.id, scheduledFor: '2026-09-07', visibility: 'plan' }); s = apply(s, 'manager', 'review.complete', { id: s.reviews[0].id, outcome: 'no_change', decision: 'Continue shared priorities.', nextReview: '2026-09-14' }); expect(s.reviews[0].sheet.feedbackIds).toContain(feedbackId); const bob = viewFor(s, person(s, 'bob')); expect(bob.reviews[0].sheet.feedbackIds).toEqual([]); expect(JSON.stringify(bob)).not.toContain(feedbackId); });
  it('rejects overly deep source chains instead of creating invisible commitments', () => { let s = fixture(); const p = alicePlan(s); let sourceType = 'plan'; let sourceId = p.id; let rejected = false; for (let i = 0; i < 12; i++) { try { s = apply(s, 'manager', 'action.create', { planId: p.id, ownerId: person(s, 'alice').id, description: `Chain action ${i}`, dueDate: '2026-09-14', sourceType, sourceId }); sourceType = 'action'; sourceId = s.actions.at(-1)!.id; } catch { rejected = true; break; } } expect(rejected).toBe(true); expect(viewFor(s, person(s, 'alice')).actions.length).toBe(s.actions.length); });
});
